### ISSUE TITLE
@types/react

### ISSUE THREAD

**Issue by cbepxpa3ym** [hiqdev/asset-packagist.dev#2]
Not able to install packages with non-standard names, example:
https://www.npmjs.com/package/@types/react

This is how your page looks like (it is broken!): 
https://asset-packagist.org/package/detail?fullname=npm-asset/%40types/react

**Comment by hiqsol** [comment]
This npm feature is called scoped packages.

Please see this issue: https://github.com/hiqdev/asset-packagist/issues/54

I close this issue. If you still have questions please open new issue in [asset-packagist](https://github.com/hiqdev/asset-packagist) package.
