### ISSUE TITLE
Can't install npm-asset/react 16.2.* as commit sha is n/a

### ISSUE THREAD

**Issue by anyt** [hiqdev/asset-packagist.dev#4]
https://asset-packagist.org/package/npm-asset/react
I'm trying to add react to the project with 
```
        "npm-asset/react": "16.2.*",
        "npm-asset/react-dom": "16.2.*"
```

but composer doesn't install anything, seems it's because of no commit sha in the asset-packagist website for new versions of the package.

I noticed that newest version of react has different package.json fields https://github.com/facebook/react/blob/v16.2.0/package.json 
when the old one had different structure
https://github.com/facebook/react/blob/v0.13.3/package.json

**Comment by hiqsol** [comment]
There is something wrong with your `composer.json`.
Here is the test one working fine for me:

```json
{
    "require": {
        "npm-asset/react": "16.2.*",
        "npm-asset/react-dom": "16.2.*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        }
    ]
}
```
